### ISSUE TITLE
Tracking for 1.0

### ISSUE THREAD

**Issue by oniatus** [oniatus/MenschAergereDichNicht#1]
- [x] World generator for a lobby
- [x] Spawn board & entities
- [x] Implement game logic
- [x] Implement random AI
- [x] Throw dice and track results to one entity
- [x] Present game state with entities 
- [ ] Smooth transitions for movement
- [ ] Use input from player (dice throw and piece selection)
- [ ] Interface for possible actions (dice throw indicator & selectable piece notification - e.g. a light effect)
- [ ] (NUI) Matchmaking instead/in addition to command matchmaking
- [ ] Multiplayer support/testing
- [ ] Persistence of gamestates over a restart
- [ ] Multiple games in parallel testing
